// Placeholder entry point for @tecode/core. Real wiring lands in later tasks.
export {
  checkApiVersionCompatibility,
  createExtensionHost,
  createHostLog,
  createNoopStatusSink,
  discover,
  getUserExtensionsDir,
  getWorkspaceExtensionsDir,
  HOST_PLACEHOLDER,
  loadExtensions,
  registerExtension,
  validateManifest,
  type ActivationState,
  type ApiVersionCompatibility,
  type ConfigRegistrar,
  type DiscoveredExtension,
  type DiscoveryDeps,
  type DiscoveryFs,
  type ExtensionHost,
  type ExtensionHostDeps,
  type ExtensionModule,
  type ExtensionRecord,
  type ExtensionSource,
  type HostError,
  type HostLog,
  type HostLogEntry,
  type HostLogLevel,
  type LoadedExtension,
  type LoadExtensionsDeps,
  type LoadExtensionsResult,
  type ManifestValidationResult,
  type PendingLanguageContribution,
  type PendingThemeContribution,
  type PendingViewContribution,
  type RegisterExtensionDeps,
  type RegisterExtensionResult,
  type SkippedExtension,
  type StatusSink,
} from "./host/index";
export {
  createCommandRegistry,
  isValidCommandId,
  type CommandRegistry,
  type CommandRegistryDeps,
  type RegisterLazyOptions,
} from "./commands/index";
export {
  CHORD_TIMEOUT_MS,
  compileWhen,
  createBindingTable,
  createChordStateMachine,
  createContextService,
  normalizeKey,
  normalizeKeySequence,
  WhenParseError,
  type BindingLayer,
  type BindingTable,
  type BindingTableDeps,
  type ChordScheduler,
  type ChordStateMachine,
  type ChordStateMachineDeps,
  type CompiledWhen,
  type ContextService,
  type KeymapLayers,
  type ResolvedBinding,
  type WhenAndNode,
  type WhenContextGetter,
  type WhenEqNode,
  type WhenKeyNode,
  type WhenNode,
  type WhenNotNode,
  type WhenOrNode,
} from "./keymap/index";
export {
  createDocument,
  createDocumentManager,
  createLineBuffer,
  createSystemClock,
  createUndoStack,
  LARGE_FILE_THRESHOLD_BYTES,
  pathToUri,
  TYPING_COALESCE_WINDOW_MS,
  uriToPath,
  type AppliedEdit,
  type ApplyEditsOptions,
  type Clock,
  type CoreDocument,
  type CreateDocumentOptions,
  type DocumentManager,
  type DocumentManagerDeps,
  type DocumentManagerFs,
  type LineBuffer,
  type PushInput,
  type TypingCoalesceHint,
  type UndoEntry,
  type UndoStack,
  type UndoStackDeps,
} from "./buffer/index";
export { UI_PLACEHOLDER } from "./ui/index";
export {
  createConfigService,
  parseJsonc,
  type ConfigService,
  type ConfigServiceDeps,
  type ConfigServiceFs,
  type JsoncFailure,
  type JsoncParseResult,
  type JsoncSuccess,
} from "./config/index";
export { API_BUILDER_PLACEHOLDER } from "./api/index";
