// Placeholder entry point for @tecode/core. Real wiring lands in later tasks.
export {
  checkApiVersionCompatibility,
  createExtensionHost,
  createHostLog,
  createNoopStatusSink,
  discover,
  getUserConfigDir,
  getUserExtensionsDir,
  getWorkspaceExtensionsDir,
  HOST_PLACEHOLDER,
  loadExtensions,
  registerExtension,
  validateManifest,
  type ActivationState,
  type ApiVersionCompatibility,
  type ConfigRegistrar,
  type DiscoveredExtension,
  type DiscoveryDeps,
  type DiscoveryFs,
  type ExtensionHost,
  type ExtensionHostDeps,
  type ExtensionModule,
  type ExtensionRecord,
  type ExtensionSource,
  type HostError,
  type HostLog,
  type HostLogEntry,
  type HostLogLevel,
  type LoadedExtension,
  type LoadExtensionsDeps,
  type LoadExtensionsResult,
  type ManifestValidationResult,
  type PendingLanguageContribution,
  type PendingThemeContribution,
  type PendingViewContribution,
  type RegisterExtensionDeps,
  type RegisterExtensionResult,
  type SkippedExtension,
  type StatusSink,
} from "./host/index";
export {
  createCommandRegistry,
  isValidCommandId,
  type CommandRegistry,
  type CommandRegistryDeps,
  type RegisterLazyOptions,
} from "./commands/index";
export {
  CHORD_TIMEOUT_MS,
  compileWhen,
  createBindingTable,
  createChordStateMachine,
  createContextService,
  keyEventToStroke,
  normalizeKey,
  normalizeKeySequence,
  WhenParseError,
  type BindingLayer,
  type BindingTable,
  type BindingTableDeps,
  type ChordScheduler,
  type ChordStateMachine,
  type ChordStateMachineDeps,
  type CompiledWhen,
  type ContextService,
  type KeyEventLike,
  type KeymapLayers,
  type ResolvedBinding,
  type WhenAndNode,
  type WhenContextGetter,
  type WhenEqNode,
  type WhenKeyNode,
  type WhenNode,
  type WhenNotNode,
  type WhenOrNode,
} from "./keymap/index";
export {
  createDocument,
  createDocumentManager,
  createLineBuffer,
  createSystemClock,
  createUndoStack,
  LARGE_FILE_THRESHOLD_BYTES,
  pathToUri,
  TYPING_COALESCE_WINDOW_MS,
  uriToPath,
  type AppliedEdit,
  type ApplyEditsOptions,
  type Clock,
  type CoreDocument,
  type CreateDocumentOptions,
  type DocumentManager,
  type DocumentManagerDeps,
  type DocumentManagerFs,
  type LineBuffer,
  type PushInput,
  type TypingCoalesceHint,
  type UndoEntry,
  type UndoStack,
  type UndoStackDeps,
  createFileSystem,
  type FileSystemDeps,
} from "./buffer/index";
export {
  ActivityBar,
  applyColorThemeSetting,
  applyConfiguredTheme,
  BASE_THEME_ID,
  BASE_THEME_LABEL,
  buildXterm256Palette,
  cellWidth,
  cellWidthUpTo,
  CHORD_PENDING_STATUS_BAR_ITEM_ID,
  CHORD_PENDING_STATUS_BAR_PRIORITY,
  computeVisibleLineRange,
  ContextFocusTracker,
  createChordPendingIndicator,
  createEditorSessionService,
  createFindService,
  createHostErrorStatusSink,
  createInitialEditorState,
  createInitialFindState,
  createLayoutStateService,
  createModalService,
  createOpenFileCommandHandler,
  createCloseDocumentWithPrompt,
  createSlotRegistry,
  createTabCommandHandlers,
  createThemeRegistry,
  createThemeSelectHandler,
  createThemeService,
  createThemeSettingsWriter,
  createWindowMessageService,
  cursorCellColumn,
  DEFAULT_HOST_ERROR_TIMEOUT_MS,
  DEFAULT_LAYOUT_STATE,
  DEFAULT_MESSAGE_TIMEOUT_MS,
  EditorArea,
  EditorView,
  filterQuickPickItems,
  FindWidget,
  gutterDigitWidth,
  HIDDEN_FROM_LISTINGS_WHEN,
  HOST_ERROR_STATUS_BAR_ITEM_ID,
  HOST_ERROR_STATUS_BAR_PRIORITY,
  INPUT_BOX_FOCUS_CONTEXT_KEY,
  Input,
  List,
  loadThemeFallbackForReadError,
  loadThemeFromJsonText,
  MODAL_ACCEPT_COMMAND,
  MODAL_CLOSE_COMMAND,
  MODAL_DEFAULT_KEYBINDINGS,
  MODAL_SELECT_NEXT_COMMAND,
  MODAL_SELECT_PREVIOUS_COMMAND,
  ModalOverlay,
  OPEN_FILE_COMMAND_ID,
  Panel,
  parseHexColor,
  quantizeTheme,
  quantizeToXterm256,
  QUICK_PICK_FOCUS_CONTEXT_KEY,
  RegisteredView,
  registerModalCommands,
  registerOpenFileCommand,
  registerTabCommands,
  registerThemeSelectCommand,
  resolveCaptureStyle,
  revealLine,
  Shell,
  Sidebar,
  StatusBar,
  TAB_CLOSE_COMMAND,
  TAB_CLOSE_OTHERS_COMMAND,
  TAB_DEFAULT_KEYBINDINGS,
  TAB_DIRTY_MARKER,
  TAB_NEXT_COMMAND,
  TAB_PREVIOUS_COMMAND,
  Tabs,
  ThemeProvider,
  toColorInput,
  Tree,
  styleToTextColors,
  useFocusTracking,
  useLineTicks,
  useLiveTheme,
  useTheme,
  wireEditorLangIdContext,
  wireThemeConfigSync,
  WINDOW_MESSAGE_STATUS_BAR_ITEM_ID,
  type ActivityBarProps,
  type ChordPendingIndicatorDeps,
  type CloseOutcome,
  type ColorDepth,
  type ContextFocusTrackerProps,
  type EditorAreaProps,
  type EditorSessionService,
  type EditorSessionServiceDeps,
  type EditorState,
  type EditorViewProps,
  type FindService,
  type FindServiceDeps,
  type FindState,
  type FindWidgetProps,
  type FocusableNode,
  type FocusEmitter,
  type HostErrorStatusSink,
  type HostErrorStatusSinkDeps,
  type InputProps,
  type LayoutState,
  type LayoutStateFs,
  type LayoutStateService,
  type LayoutStateServiceDeps,
  type LayoutStateTimer,
  type LineTicks,
  type ListItem,
  type ListProps,
  type LoadThemeOptions,
  type ModalCommandsRegistrar,
  type ModalOverlayProps,
  type ModalService,
  type ModalState,
  type OpenFileCommandDeps,
  type PanelProps,
  type RegisterViewMeta,
  type ShellProps,
  type SidebarPair,
  type SidebarProps,
  type SlotRegistry,
  type SlotRegistryDeps,
  type SlotViewEntry,
  type StatusBarPlacement,
  type StatusBarProps,
  type TabCommandHandlers,
  type TabCommandsDeps,
  type TabCommandsRegistrar,
  type TabItem,
  type TabsProps,
  type ThemeJson,
  type ThemeListEntry,
  type ThemeProviderProps,
  type ThemeRegistry,
  type ThemeRegistryDeps,
  type ThemeRegistryEntry,
  type ThemeRegistryFs,
  type ThemeSelectDeps,
  type ThemeService,
  type ThemeServiceDeps,
  type ThemeSettingsWriter,
  type ThemeSettingsWriterDeps,
  type ThemeSettingsWriterFs,
  type ThemeTokenStyleJson,
  type TreeNode,
  type TreeProps,
  type VisibleLineRange,
  type WindowMessageService,
  type WindowMessageServiceDeps,
  type WireEditorLangIdContextDeps,
  type WireThemeConfigSyncDeps,
} from "./ui/index";
export {
  createAssetResolver,
  createHighlightService,
  createLanguageRegistry,
  createWebTreeSitterParserBackend,
  PLAINTEXT_LANGUAGE_ID,
  type AssetResolver,
  type AssetResolverDeps,
  type AssetResolverFs,
  type HighlightService,
  type HighlightServiceDeps,
  type HighlightSpan,
  type LanguageRegistry,
  type LanguageRegistryEntry,
  type ParserBackend,
  type ParserCapture,
  type ParserEditDescriptor,
  type ParserLanguageHandle,
  type ParserPoint,
  type ParserQuery,
  type ParserRange,
  type ParserTree,
  type WebTreeSitterParserBackendDeps,
} from "./languages/index";
export {
  CORE_CONFIGURATION,
  createConfigService,
  DEFAULT_COLOR_THEME_ID,
  parseJsonc,
  registerCoreConfiguration,
  type ConfigService,
  type ConfigServiceDeps,
  type ConfigServiceFs,
  type CoreConfigRegistrar,
  type JsoncFailure,
  type JsoncParseResult,
  type JsoncSuccess,
} from "./config/index";
export {
  createBaseTheme,
  createEditorStub,
  createFindStub,
  createLanguagesStub,
  createTecodeApi,
  createThemesStub,
  createWindowStub,
  registerTecodeAlias,
  type CreateTecodeApiDeps,
  type LanguagesStub,
  type ThemesStub,
  type WindowStub,
} from "./api/index";
export {
  buildReplaceAllEdits,
  buildReplaceEdit,
  computeMatches,
  comparePositions,
  createEditorInputRouter,
  transformPosition,
  type EditorInputRouter,
  type EditorInputRouterDeps,
  type LineReader,
} from "./editor/index";
