// Placeholder entry point for @tecode/core. Real wiring lands in later tasks.
export {
  checkApiVersionCompatibility,
  createExtensionHost,
  createHostLog,
  createNoopStatusSink,
  discover,
  getUserConfigDir,
  getUserExtensionsDir,
  getWorkspaceExtensionsDir,
  HOST_PLACEHOLDER,
  loadExtensions,
  registerExtension,
  validateManifest,
  type ActivationState,
  type ApiVersionCompatibility,
  type ConfigRegistrar,
  type DiscoveredExtension,
  type DiscoveryDeps,
  type DiscoveryFs,
  type ExtensionHost,
  type ExtensionHostDeps,
  type ExtensionModule,
  type ExtensionRecord,
  type ExtensionSource,
  type HostError,
  type HostLog,
  type HostLogEntry,
  type HostLogLevel,
  type LoadedExtension,
  type LoadExtensionsDeps,
  type LoadExtensionsResult,
  type ManifestValidationResult,
  type PendingLanguageContribution,
  type PendingThemeContribution,
  type PendingViewContribution,
  type RegisterExtensionDeps,
  type RegisterExtensionResult,
  type SkippedExtension,
  type StatusSink,
} from "./host/index";
export {
  createCommandRegistry,
  isValidCommandId,
  type CommandRegistry,
  type CommandRegistryDeps,
  type RegisterLazyOptions,
} from "./commands/index";
export {
  CHORD_TIMEOUT_MS,
  compileWhen,
  createBindingTable,
  createChordStateMachine,
  createContextService,
  normalizeKey,
  normalizeKeySequence,
  WhenParseError,
  type BindingLayer,
  type BindingTable,
  type BindingTableDeps,
  type ChordScheduler,
  type ChordStateMachine,
  type ChordStateMachineDeps,
  type CompiledWhen,
  type ContextService,
  type KeymapLayers,
  type ResolvedBinding,
  type WhenAndNode,
  type WhenContextGetter,
  type WhenEqNode,
  type WhenKeyNode,
  type WhenNode,
  type WhenNotNode,
  type WhenOrNode,
} from "./keymap/index";
export {
  createDocument,
  createDocumentManager,
  createLineBuffer,
  createSystemClock,
  createUndoStack,
  LARGE_FILE_THRESHOLD_BYTES,
  pathToUri,
  TYPING_COALESCE_WINDOW_MS,
  uriToPath,
  type AppliedEdit,
  type ApplyEditsOptions,
  type Clock,
  type CoreDocument,
  type CreateDocumentOptions,
  type DocumentManager,
  type DocumentManagerDeps,
  type DocumentManagerFs,
  type LineBuffer,
  type PushInput,
  type TypingCoalesceHint,
  type UndoEntry,
  type UndoStack,
  type UndoStackDeps,
  createFileSystem,
  type FileSystemDeps,
} from "./buffer/index";
export {
  ActivityBar,
  cellWidth,
  cellWidthUpTo,
  computeVisibleLineRange,
  ContextFocusTracker,
  createInitialEditorState,
  createLayoutStateService,
  createSlotRegistry,
  cursorCellColumn,
  DEFAULT_LAYOUT_STATE,
  EditorArea,
  EditorView,
  gutterDigitWidth,
  Input,
  List,
  Panel,
  RegisteredView,
  revealLine,
  Shell,
  Sidebar,
  StatusBar,
  Tabs,
  ThemeProvider,
  toColorInput,
  Tree,
  styleToTextColors,
  useFocusTracking,
  useLineTicks,
  useTheme,
  type ActivityBarProps,
  type ContextFocusTrackerProps,
  type EditorAreaProps,
  type EditorState,
  type EditorViewProps,
  type FocusEmitter,
  type InputProps,
  type LayoutState,
  type LayoutStateFs,
  type LayoutStateService,
  type LayoutStateServiceDeps,
  type LayoutStateTimer,
  type LineTicks,
  type ListItem,
  type ListProps,
  type PanelProps,
  type RegisterViewMeta,
  type ShellProps,
  type SidebarPair,
  type SidebarProps,
  type SlotRegistry,
  type SlotRegistryDeps,
  type SlotViewEntry,
  type StatusBarPlacement,
  type StatusBarProps,
  type TabItem,
  type TabsProps,
  type ThemeProviderProps,
  type TreeNode,
  type TreeProps,
  type VisibleLineRange,
} from "./ui/index";
export {
  CORE_CONFIGURATION,
  createConfigService,
  parseJsonc,
  registerCoreConfiguration,
  type ConfigService,
  type ConfigServiceDeps,
  type ConfigServiceFs,
  type CoreConfigRegistrar,
  type JsoncFailure,
  type JsoncParseResult,
  type JsoncSuccess,
} from "./config/index";
export {
  createBaseTheme,
  createEditorStub,
  createLanguagesStub,
  createTecodeApi,
  createThemesStub,
  createWindowStub,
  registerTecodeAlias,
  type CreateTecodeApiDeps,
  type LanguagesStub,
  type ThemesStub,
  type WindowStub,
} from "./api/index";
